import { writable } from "svelte/store"

const EditorValue = writable("")

const EditorTarget = writable("/home/iamfiasco/deardiary/today.md")

const EditorFType = writable("markdown")

let modes = [
    "javascript",
    "abap",
    "abc",
    "actionscript",
    "ada",
    "alda",
    "apache conf",
    "apex",
    "aql",
    "asciidoc",
    "asl",
    "assembly x86",
    "autohotkey / autoit",
    "batchfile",
    "c and c++",
    "c#",
    "c9 search results",
    "cirru",
    "clojure",
    "cobol",
    "coffeescript",
    "coldfusion",
    "crystal",
    "csound",
    "csound document",
    "csound score",
    "css",
    "curly",
    "d",
    "dart",
    "diff",
    "django",
    "dockerfile",
    "dot",
    "drools",
    "edifact",
    "eiffel",
    "ejs",
    "elixir",
    "elm",
    "erlang",
    "forth",
    "fortran",
    "freemarker",
    "fsharp",
    "fsl",
    "gcode",
    "gherkin",
    "gitignore",
    "glsl",
    "go",
    "gobstones",
    "graphqlschema",
    "groovy",
    "haml",
    "handlebars",
    "haskell",
    "haskell cabal",
    "haxe",
    "hjson",
    "html",
    "html (elixir)",
    "html (ruby)",
    "ini",
    "io",
    "ion",
    "jack",
    "jade",
    "java",
    "json",
    "json5",
    "jsoniq",
    "jsp",
    "jssm",
    "jsx",
    "julia",
    "kotlin",
    "latex",
    "latte",
    "less",
    "liquid",
    "lisp",
    "livescript",
    "log",
    "logiql",
    "lsl",
    "lua",
    "luapage",
    "lucene",
    "makefile",
    "markdown",
    "mask",
    "matlab",
    "maze",
    "mediawiki",
    "mel",
    "mips",
    "mixal",
    "mushcode",
    "mysql",
    "nginx",
    "nim",
    "nix",
    "nix",
    "nsis",
    "nunjucks",
    "objective-c",
    "ocaml",
    "partiql",
    "pascal",
    "perl",
    "pgsql",
    "php",
    "php (blade template)",
    "pig",
    "plain text",
    "powershell",
    "praat",
    "prisma",
    "prolog",
    "properties",
    "protobuf",
    "puppet",
    "python",
    "qml",
    "r",
    "raku",
    "razor",
    "rdoc",
    "red",
    "rhtml",
    "robot",
    "rst",
    "ruby",
    "rust",
    "sac",
    "sass",
    "scad",
    "scala",
    "scheme",
    "scrypt",
    "scss",
    "sh",
    "sjs",
    "slim",
    "smarty",
    "smithy",
    "snippets",
    "soy template",
    "space",
    "sql",
    "sqlserver",
    "stylus",
    "svg",
    "swift",
    "tcl",
    "terraform",
    "tex",
    "text",
    "textile",
    "toml",
    "tsx",
    "twig",
    "typescript",
    "vala",
    "vbscript",
    "velocity",
    "verilog",
    "vhdl",
    "visualforce",
    "wollok",
    "xml",
    "xquery",
    "yaml",
    "zeek"
]

const EditorModes = writable(modes)

export { EditorValue, EditorTarget, EditorFType, EditorModes }


